/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // HarvestHub / Harvest Harmony design system
        'on-tertiary-fixed': '#001f29',
        'surface-bright': '#fef9f0',
        'on-tertiary-fixed-variant': '#004d62',
        'background': '#fef9f0',
        'tertiary-fixed': '#baeaff',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#42493d',
        'on-secondary-container': '#77330f',
        'on-primary-fixed': '#052100',
        'on-secondary-fixed-variant': '#76320f',
        'primary-fixed-dim': '#9dd684',
        'on-tertiary-container': '#eff9ff',
        'tertiary': '#00617a',
        'outline-variant': '#c2c9b9',
        'primary': '#336421',
        'on-primary-fixed-variant': '#20510f',
        'inverse-surface': '#32302a',
        'on-primary': '#ffffff',
        'on-background': '#1d1c16',
        'surface-variant': '#e7e2d9',
        'tertiary-fixed-dim': '#89d0ed',
        'error': '#ba1a1a',
        'surface-container-low': '#f8f3ea',
        'primary-container': '#4b7e37',
        'on-surface': '#1d1c16',
        'error-container': '#ffdad6',
        'on-primary-container': '#e8ffd8',
        'secondary-fixed': '#ffdbcd',
        'surface-tint': '#386a25',
        'secondary-fixed-dim': '#ffb596',
        'on-secondary-fixed': '#360f00',
        'secondary-container': '#ff9e72',
        'on-secondary': '#ffffff',
        'surface-container': '#f2ede4',
        'inverse-on-surface': '#f5f0e7',
        'on-error-container': '#93000a',
        'surface-dim': '#ded9d1',
        'surface': '#fef9f0',
        'inverse-primary': '#9dd684',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#2d7a94',
        'secondary': '#954924',
        'primary-fixed': '#b8f29d',
        'outline': '#72796c',
        'surface-container-highest': '#e7e2d9',
        'surface-container-high': '#ece8df',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'base': '8px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '24px',
        'margin': '32px',
      },
      fontFamily: {
        'h1': ['Plus Jakarta Sans'],
        'h2': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'h1': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'h2': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        'inner-highlight': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.4)',
        'tactile': '0 2px 0 0 rgba(0, 0, 0, 0.1)',
        'tactile-lg': '0 4px 0 0 #77330f',
        'plot-card': '0 4px 12px -2px rgba(75, 126, 55, 0.15)',
      },
    },
  },
  plugins: [],
}
